// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_e_commerce/test/login/login_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i7;
import 'package:flutter_e_commerce/features/authentication/domain/model/oauth.dart'
    as _i2;
import 'package:flutter_e_commerce/features/authentication/domain/model/user.dart'
    as _i3;
import 'package:flutter_e_commerce/features/authentication/domain/model/user_info.dart'
    as _i9;
import 'package:flutter_e_commerce/features/authentication/domain/service/auth_local_repository.dart'
    as _i10;
import 'package:flutter_e_commerce/features/authentication/infrastructure/data/platzi_auth_api.dart'
    as _i5;
import 'package:flutter_e_commerce/features/authentication/infrastructure/data/platzi_user_api.dart'
    as _i8;
import 'package:flutter_e_commerce/features/authentication/infrastructure/model/user_available.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOAuth_0 extends _i1.SmartFake implements _i2.OAuth {
  _FakeOAuth_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserAvailable_2 extends _i1.SmartFake implements _i4.UserAvailable {
  _FakeUserAvailable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlatziAuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatziAuthApi extends _i1.Mock implements _i5.PlatziAuthApi {
  @override
  _i6.Future<_i2.OAuth> login({
    required Map<String, dynamic>? credential,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #credential: credential,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i2.OAuth>.value(_FakeOAuth_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #credential: credential,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.OAuth>.value(_FakeOAuth_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #credential: credential,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i2.OAuth>);

  @override
  _i6.Future<_i2.OAuth> refresh({
    required Map<String, dynamic>? refresh,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
          {
            #refresh: refresh,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i2.OAuth>.value(_FakeOAuth_0(
          this,
          Invocation.method(
            #refresh,
            [],
            {
              #refresh: refresh,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.OAuth>.value(_FakeOAuth_0(
          this,
          Invocation.method(
            #refresh,
            [],
            {
              #refresh: refresh,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i2.OAuth>);

  @override
  _i6.Future<_i3.User> getUserInfo({
    required String? authToken,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [],
          {
            #authToken: authToken,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #getUserInfo,
            [],
            {
              #authToken: authToken,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #getUserInfo,
            [],
            {
              #authToken: authToken,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);
}

/// A class which mocks [PlatziUserApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatziUserApi extends _i1.Mock implements _i8.PlatziUserApi {
  @override
  _i6.Future<_i4.UserAvailable> checkAvailability({
    required Map<String, dynamic>? email,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAvailability,
          [],
          {
            #email: email,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i4.UserAvailable>.value(_FakeUserAvailable_2(
          this,
          Invocation.method(
            #checkAvailability,
            [],
            {
              #email: email,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.UserAvailable>.value(_FakeUserAvailable_2(
          this,
          Invocation.method(
            #checkAvailability,
            [],
            {
              #email: email,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.UserAvailable>);

  @override
  _i6.Future<_i3.User> createUser({
    required _i9.UserInfo? newUserInfo,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {
            #newUserInfo: newUserInfo,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #createUser,
            [],
            {
              #newUserInfo: newUserInfo,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #createUser,
            [],
            {
              #newUserInfo: newUserInfo,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);
}

/// A class which mocks [AuthenticationLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationLocalStorage<T extends _i3.UserCredential>
    extends _i1.Mock implements _i10.AuthenticationLocalStorage<T> {
  @override
  _i6.Future<T?> read() => (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
        ),
        returnValue: _i6.Future<T?>.value(),
        returnValueForMissingStub: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<void> write(T? token) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
